-- Fusion des deux listes de sources de la veille automatique (12/09/2026) --
-- ---------------------------------------------------------------------------
-- Jusqu'ici, la veille consultait deux listes séparées : les 14 lignes de
-- affut_sources_suivies (écran « Sources », visitées à CHAQUE exécution) et
-- un catalogue statique de 137 revues/bulletins dans
-- apps/affut/documents/brief-veille.md (visité une fois par mois seulement,
-- jamais éditable depuis l'app). Confusion constatée par l'utilisateur (« la
-- routine n'annonce que 14 sources suivies, on en avait pourtant écrit
-- beaucoup plus ») : les deux listes portaient presque le même nom pour des
-- rôles différents.
--
-- Cette migration fait de affut_sources_suivies la SEULE liste d'adresses à
-- consulter, hebdomadaires et mensuelles confondues, en ajoutant la
-- périodicité comme donnée plutôt que comme deux mécanismes séparés :
-- - `periodicite` : 'hebdomadaire' (visitée à chaque exécution, comme avant
--   pour les 14 sources d'origine) ou 'mensuelle' (visitée seulement à
--   l'exécution qui tombe dans la 1re semaine du mois — logique reprise de
--   la section « Revues et bulletins naturalistes » du brief) ;
-- - `notes` : le reliquat texte libre du catalogue (éditeur, thématique,
--   accès, périodicité éditoriale, remarques) — informationnel, jamais lu
--   par la mécanique de filtrage.
--
-- Import des 137 revues du catalogue en lignes `periodicite = 'mensuelle'`
-- (générées depuis brief-veille.md, voir le commit associé) — la section
-- correspondante du brief est retirée dans la foulée pour ne plus avoir
-- qu'un seul endroit où cette liste existe.

alter table affut_sources_suivies
  add column if not exists periodicite text not null default 'hebdomadaire',
  add column if not exists notes text not null default '';

alter table affut_sources_suivies
  drop constraint if exists affut_sources_suivies_periodicite_check;

alter table affut_sources_suivies
  add constraint affut_sources_suivies_periodicite_check
  check (periodicite in ('hebdomadaire', 'mensuelle'));

-- Les 14 sources existantes n'ont pas de valeur explicite : le défaut
-- 'hebdomadaire' ci-dessus leur convient déjà (comportement inchangé pour
-- elles), rien à rétrofiter.

insert into affut_sources_suivies (id, nom, adresse, type, echelle, territoire, rubrique_defaut, periodicite, notes) values
  ('revue-naturae', 'Naturae', 'https://sciencepress.mnhn.fr/fr/periodiques/naturae', 'page suivie', 'national', '', '', 'mensuelle', 'MNHN — Publications scientifiques · Généraliste · accès libre · flux continu'),
  ('revue-cryptogamie-bryologie', 'Cryptogamie, Bryologie', 'https://sciencepress.mnhn.fr/fr/periodiques/bryologie', 'page suivie', 'national', '', '', 'mensuelle', 'MNHN — Publications scientifiques · Mycologie & cryptogames · accès libre · flux continu (Accès ouvert intégral, modèle diamant.)'),
  ('revue-biodiversite-des-cles-pour-agir', 'Biodiversité, des clés pour agir', 'https://professionnels.ofb.fr/fr/revues', 'page suivie', 'national', '', '', 'mensuelle', 'OFB · Gestion & ingénierie · accès libre · trimestriel (Succède à Espaces naturels et Faune sauvage.)'),
  ('revue-espaces-naturels', 'Espaces naturels', 'http://www.espaces-naturels.info/archives', 'page suivie', 'national', '', '', 'mensuelle', 'OFB · Gestion & ingénierie · accès mixte · trimestriel · arrêtée (Présentée par l''OFB comme ancienne revue ; archives toujours en ligne.)'),
  ('revue-faune-sauvage', 'Faune sauvage', 'https://professionnels.ofb.fr/fr/doc/revue-faune-sauvage', 'page suivie', 'national', '', '', 'mensuelle', 'OFB (ex-ONCFS) · Généraliste · accès libre · trimestriel · arrêtée (Ancienne revue, archives consultables.)'),
  ('revue-cahiers-techniques', 'Cahiers techniques', 'https://cahiers-techniques.espaces-naturels.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'OFB (collection ex-ATEN) · Gestion & ingénierie · accès libre · collection (Derniers titres identifiés vers 2017.)'),
  ('revue-actualites-et-publications-patrinat', 'Actualités et publications PatriNat', 'https://www.patrinat.fr/fr/recherche/type/actualite', 'page suivie', 'national', '', '', 'mensuelle', 'PatriNat (MNHN / OFB / CNRS / IRD) · Données & référentiels · accès libre · flux continu'),
  ('revue-actualites-et-regards', 'Actualités et Regards', 'https://sfecologie.org/category/actu/', 'page suivie', 'national', '', '', 'mensuelle', 'SFE² — Société Française d''Écologie et d''Évolution · Généraliste · accès libre · flux continu'),
  ('revue-plume-de-naturalistes', 'Plume de Naturalistes', 'https://www.plume-de-naturalistes.fr/numeros/', 'page suivie', 'national', '', '', 'mensuelle', 'Revue en ligne · Généraliste · accès libre'),
  ('revue-les-carnets-natures', 'Les Carnets natures', 'https://carnetsnatures.fr/articles-publies.html', 'page suivie', 'national', '', '', 'mensuelle', 'ASNAT — Muséum de Gaillac · Généraliste · accès libre · volumes annuels'),
  ('revue-le-courrier-de-la-nature', 'Le Courrier de la Nature', 'https://www.snpn.com/courrier-nature/', 'page suivie', 'national', '', '', 'mensuelle', 'SNPN · Généraliste · adhérents/abonnement · trimestriel'),
  ('revue-zones-humides-infos', 'Zones Humides Infos', 'https://www.snpn.com/zones-humides-infos/', 'page suivie', 'national', '', '', 'mensuelle', 'SNPN · Zones humides · accès mixte (Dernier numéro identifié : n°109, décembre 2025.)'),
  ('revue-revue-decologie-la-terre-et-la-vie', 'Revue d''Écologie (La Terre et la Vie)', 'https://www.snpn.com/', 'page suivie', 'national', '', '', 'mensuelle', 'SNPN · Généraliste · adhérents/abonnement · parution incertaine (Page dédiée non confirmée ; passer par le site de la SNPN.)'),
  ('revue-especes', 'Espèces', 'https://especes.org/numeros/', 'page suivie', 'national', '', '', 'mensuelle', 'Kyrnos Publications · Généraliste · adhérents/abonnement · trimestriel'),
  ('revue-la-hulotte', 'La Hulotte', 'https://www.lahulotte.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'Éditions Passerage · Généraliste · adhérents/abonnement · semestriel'),
  ('revue-martinia', 'Martinia', 'https://martinia.insectes.org/martinia-archives/', 'page suivie', 'national', '', '', 'mensuelle', 'OPIE — groupe Odonates · Entomologie & invertébrés · accès libre (Odonatologie française et outre-mer.)'),
  ('revue-insectes', 'Insectes', 'https://insectes.org/la-revue-insectes/les-archives-de-la-revue/', 'page suivie', 'national', '', '', 'mensuelle', 'OPIE · Entomologie & invertébrés · accès libre · trimestriel (En accès libre numérique depuis 2025.)'),
  ('revue-lentomologiste', 'L''Entomologiste', 'http://lentomologiste.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'Société entomologique de France · Entomologie & invertébrés · adhérents/abonnement · bimestriel'),
  ('revue-malaco', 'MalaCo', 'https://journal-malaco.mnhn.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'MNHN — malacologie continentale · Entomologie & invertébrés · accès libre'),
  ('revue-bulletin-de-la-shf', 'Bulletin de la SHF', 'https://lashf.org/bshf/', 'page suivie', 'national', '', '', 'mensuelle', 'Société Herpétologique de France · Herpétologie · accès libre (Entièrement numérique et gratuit.)'),
  ('revue-lenvol-des-chiros', 'L''Envol des Chiros', 'https://www.sfepm.org/publications-sur-les-chauves-souris.html', 'page suivie', 'national', '', '', 'mensuelle', 'SFEPM · Mammifères & chiroptères · accès libre · irrégulier'),
  ('revue-arvicola', 'Arvicola', 'https://www.sfepm.org/publications-la-sfepm-les-mammiferes.html', 'page suivie', 'national', '', '', 'mensuelle', 'SFEPM · Mammifères & chiroptères · adhérents/abonnement · irrégulier'),
  ('revue-ornithos', 'Ornithos', 'https://www.lpo.fr/s-engager-a-nos-cotes/s-abonner-a-nos-revues/ornithos', 'page suivie', 'national', '', '', 'mensuelle', 'LPO · Ornithologie · adhérents/abonnement · trimestriel'),
  ('revue-alauda', 'Alauda', 'https://www.seof.fr/actualit-dalauda', 'page suivie', 'national', '', '', 'mensuelle', 'SEOF · Ornithologie · adhérents/abonnement'),
  ('revue-revue-forestiere-francaise', 'Revue forestière française', 'https://revueforestierefrancaise.agroparistech.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'AgroParisTech · Forêt · accès libre (Également en libre accès sur DOAJ et HAL.)'),
  ('revue-foret-innovation-ex-foret-entreprise', 'Forêt & Innovation (ex-Forêt-entreprise)', 'https://www.cnpf.fr/se-former-s-informer/nos-publications/foret-entreprise-la-revue-du-cnpf', 'page suivie', 'national', '', '', 'mensuelle', 'CNPF / IDF · Forêt · accès mixte · 6 n°/an (Numéros de plus de deux ans en téléchargement libre.)'),
  ('revue-rendez-vous-techniques-de-lonf', 'Rendez-vous techniques de l''ONF', 'https://www.onf.fr/onf/+/16c3::les-rendez-vous-techniques-de-lonf-numero-74.html', 'page suivie', 'national', '', '', 'mensuelle', 'Office National des Forêts · Forêt · accès libre · irrégulier (Lien vers un numéro ; naviguer depuis onf.fr pour la collection.)'),
  ('revue-sciences-eaux-territoires', 'Sciences Eaux & Territoires', 'https://revue-set.fr/about', 'page suivie', 'national', '', '', 'mensuelle', 'INRAE · Zones humides · accès libre · numéros thématiques (Accès ouvert intégral depuis 1995.)'),
  ('revue-ecologia-mediterranea', 'Ecologia Mediterranea', 'https://ecologia-mediterranea.univ-avignon.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'IMBE / Naturalia Publications · Gestion & ingénierie · accès mixte (Archives également sur Persée.)'),
  ('revue-le-journal-de-botanique', 'Le Journal de Botanique', 'https://societebotaniquedefrance.fr/publications/le-journal-de-botanique/', 'page suivie', 'national', '', '', 'mensuelle', 'Société Botanique de France · Botanique & phytosociologie · adhérents/abonnement · 4 n°/an'),
  ('revue-la-garance-voyageuse', 'La Garance voyageuse', 'https://garance-voyageuse.org/la-revue.html', 'page suivie', 'national', '', '', 'mensuelle', 'Association La Garance Voyageuse · Botanique & phytosociologie · adhérents/abonnement · trimestriel'),
  ('revue-carnets-botaniques', 'Carnets botaniques', 'https://sbocc.fr/carnets-botaniques/', 'page suivie', 'national', '', '', 'mensuelle', 'Société Botanique d''Occitanie · Botanique & phytosociologie · accès libre · flux continu (Accès ouvert intégral, lancée en 2020.)'),
  ('revue-documents-phytosociologiques', 'Documents phytosociologiques', 'http://www.phytosocio.org/#/doc-phyto/doc-phyto', 'page suivie', 'national', '', '', 'mensuelle', 'Société française de phytosociologie · Botanique & phytosociologie · adhérents/abonnement · annuel · parution incertaine (Conditions d''accès non confirmées.)'),
  ('revue-bulletin-de-la-societe-mycologique-de-fr', 'Bulletin de la Société Mycologique de France', 'https://www.mycofrance.fr/bulletin-de-la-smf/', 'page suivie', 'national', '', '', 'mensuelle', 'Société Mycologique de France · Mycologie & cryptogames · accès mixte · trimestriel (Numéros 1885-1990 en libre accès sur Gallica.)'),
  ('revue-bulletin-de-lassociation-francaise-de-li', 'Bulletin de l''Association Française de Lichénologie', 'https://www.sbco.fr/bulletin-de-association-francaise-de-lichenologie-50-1/', 'page suivie', 'national', '', '', 'mensuelle', 'AFL · Mycologie & cryptogames · adhérents/abonnement · parution incertaine (Site de l''AFL inaccessible en vérification ; lien vers une page tierce.)'),
  ('revue-cahiers-de-biologie-marine', 'Cahiers de Biologie Marine', 'https://cbm.sb-roscoff.fr/', 'page suivie', 'national', '', '', 'mensuelle', 'Station Biologique de Roscoff · Marin & littoral · adhérents/abonnement · 6 n°/an'),
  ('revue-vie-et-milieu', 'Vie et Milieu', 'https://wwwphp.obs-banyuls.fr/Viemilieu/index.php/contents.html', 'page suivie', 'national', '', '', 'mensuelle', 'Observatoire océanologique de Banyuls · Marin & littoral · adhérents/abonnement · parution incertaine (Conditions d''accès non confirmées.)'),
  ('revue-magazine-parcs', 'Magazine Parcs', 'https://www.parcs-naturels-regionaux.fr/mediatheque/magazines', 'page suivie', 'national', '', '', 'mensuelle', 'Fédération des Parcs naturels régionaux · Gestion & ingénierie · accès libre · semestriel (Archives depuis 1997 ; n°97 en mars 2026.)'),
  ('revue-actualites-du-reseau-des-cen', 'Actualités du réseau des CEN', 'https://reseau-cen.org/actualites/', 'page suivie', 'national', '', '', 'mensuelle', 'Fédération des Conservatoires d''espaces naturels · Gestion & ingénierie · accès libre · flux continu'),
  ('revue-a-fleur-deau', 'A fleur d''Eau', 'https://bassinversant.org/przhmva/a-fleur-deau-la-newsletter-du-pole-relais-zones-humides-mares-et-vallees-alluviales/', 'page suivie', 'national', '', '', 'mensuelle', 'Pôle-relais zones humides Mares et Vallées Alluviales · Zones humides · accès libre'),
  ('revue-escale', 'Escale', 'http://www.biodiversite-poitou-charentes.org/Lettre-d-info-Escale-no61-Pole-relais-zones-humides-du-FMA.html', 'page suivie', 'national', '', '', 'mensuelle', 'Pôle-relais zones humides — Forum des Marais Atlantiques · Zones humides · accès libre (Lien vers le n°61 ; collection à parcourir depuis le site du FMA.)'),
  ('revue-ar-vran', 'Ar Vran', 'https://www.bretagne-vivante.org/decouverte-de-la-nature/nos-revues/', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'Bretagne Vivante · Ornithologie · accès mixte · annuel'),
  ('revue-penn-ar-bed', 'Penn ar Bed', 'https://www.bretagne-vivante.org/decouverte-de-la-nature/nos-revues/', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'Bretagne Vivante · Généraliste · adhérents/abonnement · trimestriel (Paraît depuis 1953.)'),
  ('revue-invertebres-armoricains-cahiers-du-greti', 'Invertébrés Armoricains — Cahiers du GRETIA', 'http://www.gretia.org/index.php/connaissances/invertebres-armoricains-les-cahiers-du-gretia', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'GRETIA · Entomologie & invertébrés · accès mixte · irrégulier (Couvre aussi Normandie et Pays de la Loire.)'),
  ('revue-mammibreizh', 'Mammi''Breizh', 'https://gmb.bzh/type_doc/bulletin/', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'Groupe Mammalogique Breton · Mammifères & chiroptères · adhérents/abonnement · semestriel'),
  ('revue-le-rale-deau', 'Le Râle d''eau', 'https://www.vivarmor.fr/lassociation/notre-bulletin-dinformation/', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'VivArmor Nature · Généraliste · accès mixte · trimestriel (Côtes-d''Armor. Archives libres à partir du n°181.)'),
  ('revue-e-r-i-c-a', 'E.R.I.C.A.', 'https://www.cbnbrest.fr/espace-documentaire/erica', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'Conservatoire botanique national de Brest · Botanique & phytosociologie · accès libre · annuel (Flore armoricaine ; n°40 paru en juillet 2026.)'),
  ('revue-bulletin-de-liaison', 'Bulletin de liaison', 'https://finistere.lpo.fr/index.php/bulletin-de-liaison', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'LPO Finistère · Ornithologie · adhérents/abonnement'),
  ('revue-bulletin-mycologique', 'Bulletin mycologique', 'https://bretagne-environnement.fr/organisme/Societe-mycologique-Rennes', 'page suivie', 'régional', 'Bretagne', '', 'mensuelle', 'Société mycologique de Rennes · Mycologie & cryptogames · adhérents/abonnement · trimestriel · parution incertaine'),
  ('revue-lettre-dinformation', 'Lettre d''information', 'https://cenpaysdelaloire.fr/lettre-d-information-0', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'CEN Pays de la Loire · Gestion & ingénierie · accès libre · trimestriel'),
  ('revue-le-crex', 'Le Crex', 'https://www.faune-paysdelaloire.org/index.php?m_id=20938', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'LPO Anjou · Ornithologie · adhérents/abonnement'),
  ('revue-sur-les-chemins-de-lacampagne-ex-le-tari', 'Sur les chemins de Lacampagne (ex-Le Tarier pâtre)', 'https://sarthe.lpo.fr/lpo-sarthe/nos-publications/tarier-patre-sur-les-chemins-de-lacampagne/', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'LPO Sarthe · Ornithologie · accès libre · annuel (PDF disponibles depuis 2000.)'),
  ('revue-le-naturaliste-vendeen', 'Le Naturaliste Vendéen', 'https://naturalistes-vendeens.org/revue-scientifique-le-naturaliste-vendeen/', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'Les Naturalistes Vendéens · Généraliste · adhérents/abonnement · annuel (Faune, flore et paléontologie.)'),
  ('revue-la-gorgebleue-lpo-infos-vendee', 'La Gorgebleue / LPO infos Vendée', 'https://vendee.lpo.fr/nos-actions/informer/publications-de-lpo-vendee/', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'LPO Vendée · Ornithologie · accès mixte'),
  ('revue-publications-naturalistes', 'Publications naturalistes', 'https://www.mayennenatureenvironnement.fr/nos-publications/', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'Mayenne Nature Environnement · Généraliste · adhérents/abonnement · parution incertaine'),
  ('revue-cahiers-mycologiques', 'Cahiers Mycologiques', 'https://amo-nantes.fr/', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'Association Mycologique de l''Ouest (Nantes) · Mycologie & cryptogames · accès libre · annuel (Numéros 1989-2022 en téléchargement gratuit.)'),
  ('revue-anjou-nature', 'Anjou Nature', 'https://anjou-nature-la-revue-des-naturalistes-angevins-1.jimdosite.com/bulletins-publies', 'page suivie', 'régional', 'Pays de la Loire', '', 'mensuelle', 'Les Naturalistes Angevins · Généraliste · accès mixte · arrêtée (Cinq numéros ; arrêtée en 2015.)'),
  ('revue-le-cormoran-le-petit-cormoran', 'Le Cormoran / Le Petit Cormoran', 'https://www.gonm.org/index.php?post/Le-Cormoran', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'Groupe Ornithologique Normand · Ornithologie · adhérents/abonnement · mensuel (Petit Cormoran)'),
  ('revue-le-petit-lerot', 'Le Petit Lérot', 'https://new.gmn.asso.fr/publications/', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'Groupe Mammalogique Normand · Mammifères & chiroptères · adhérents/abonnement'),
  ('revue-nature-en-scene-normandie', 'Nature en sCENe Normandie', 'http://cen-normandie.fr/publications/la-vie-des-conservatoires/lettres-d-informations', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'CEN Normandie · Gestion & ingénierie · accès libre'),
  ('revue-largiope', 'L''Argiope', 'https://manche-nature.fr/publications/', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'Manche-Nature · Généraliste · adhérents/abonnement · trimestriel'),
  ('revue-les-dossiers-de-manche-nature', 'Les Dossiers de Manche-Nature', 'https://manche-nature.fr/publications/', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'Manche-Nature · Généraliste · adhérents/abonnement · irrégulier (Monographies thématiques ; 11 volumes depuis 1997.)'),
  ('revue-bulletin-de-la-sasnmr', 'Bulletin de la SASNMR', 'https://sasnmr.fr/bulletins', 'page suivie', 'régional', 'Normandie', '', 'mensuelle', 'Amis des Sciences Naturelles et du Muséum de Rouen · Généraliste · adhérents/abonnement (Société fondée en 1865.)'),
  ('revue-recherches-naturalistes', 'Recherches Naturalistes', 'https://fne-centrevaldeloire.org/recherches-naturalistes', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'FNE Centre-Val de Loire · Généraliste · adhérents/abonnement · irrégulier · parution incertaine (Dernier numéro repéré : n°13, mars 2022.)'),
  ('revue-expli-sites', 'Expli-Sites', 'https://www.cen-centrevaldeloire.org/telechargements/6-Bulletins-dinformations/', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'CEN Centre-Val de Loire · Gestion & ingénierie · accès libre'),
  ('revue-le-ptit-grav', 'Le P''tit Grav''', 'https://faune-indre-et-loire.org/index.php?langu=en&m_id=21127', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'LPO Centre-Val de Loire · Ornithologie · adhérents/abonnement · annuel'),
  ('revue-armeria', 'Armeria', 'http://www.cpievaldeloire.org/armeria-bulletin-naturaliste/', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'CPIE Touraine — Val de Loire · Généraliste · adhérents/abonnement'),
  ('revue-bulletin-annuel', 'Bulletin annuel', 'https://www.perchenature.fr/wp-content/uploads/2025/01/bulletin-annuel-perche-nature-2023-red.pdf', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'Perche Nature · Généraliste · accès libre · annuel (Lien vers l''édition 2023.)'),
  ('revue-geai', 'GEAI', 'https://www.indrenature.net/nos-publications', 'page suivie', 'régional', 'Centre-Val de Loire', '', 'mensuelle', 'Indre Nature · Généraliste · adhérents/abonnement'),
  ('revue-lavocette', 'L''Avocette', 'https://www.picardie-nature.org/l-association/picardie-nature-edition/l-avocette-revue-naturaliste-de/', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'Picardie Nature · Généraliste · accès mixte · semestriel (Oiseaux, chiroptères, amphibiens de Picardie.)'),
  ('revue-le-heron', 'Le Héron', 'https://gon.fr/ressources/', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'Groupe Ornithologique et Naturaliste (GON) · Ornithologie · adhérents/abonnement · semestriel'),
  ('revue-lettres-dinfos-des-hauts-de-france', 'Lettres d''infos des Hauts-de-France', 'https://www.cen-hautsdefrance.org/publications/les-lettres-d-infos-des-hauts-de-france', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'CEN Hauts-de-France · Gestion & ingénierie · accès libre'),
  ('revue-bulletin-de-la-societe-linneenne-nord-pi', 'Bulletin de la Société linnéenne Nord-Picardie', 'https://www.linneenne-amiens.org/?page_id=445', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'Société linnéenne Nord-Picardie · Généraliste · accès libre · annuel (Botanique, faune, mycologie, habitats.)'),
  ('revue-nature-en-hauts-de-france', 'Nature en Hauts-de-France', 'https://www.observatoire-biodiversite-hdf.fr/publications/nature-en-hauts-de-france', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'Observatoire régional de la biodiversité · Données & référentiels · accès libre'),
  ('revue-bulletin-de-la-societe-de-botanique-du-n', 'Bulletin de la Société de botanique du nord de la France', 'https://societebotaniquenord.wordpress.com/', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'SBNF · Botanique & phytosociologie · accès libre · annuel (Archives PDF, tomes 74 (2021) et 75 (2022).)'),
  ('revue-documents-mycologiques', 'Documents Mycologiques', 'https://www.smnf.fr/index.php/les-documents-mycologiques-2/', 'page suivie', 'régional', 'Hauts-de-France', '', 'mensuelle', 'Société Mycologique du Nord de la France · Mycologie & cryptogames · adhérents/abonnement · arrêtée (Arrêt annoncé après le tome XXXVII (2019).)'),
  ('revue-ciconia', 'Ciconia', 'https://alsace.lpo.fr/index.php/nos-publications/livres', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'LPO Alsace · Ornithologie · adhérents/abonnement · annuel (Écologie animale ; volumes numérotés depuis les années 1970.)'),
  ('revue-magazine-des-3-cen', 'Magazine des 3 CEN', 'https://www.conservatoire-sites-alsaciens.eu/publications/magazine-des-3-cen/', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'CEN Alsace, Lorraine et Champagne-Ardenne · Gestion & ingénierie · accès libre · annuel'),
  ('revue-publications-du-cen-alsace', 'Publications du CEN Alsace', 'https://www.conservatoire-sites-alsaciens.eu/publications/', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'CEN Alsace (ex-CSA) · Gestion & ingénierie · accès libre'),
  ('revue-espaces-naturels-de-lorraine', 'Espaces Naturels de Lorraine', 'https://cen-lorraine.fr/', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'CEN Lorraine · Gestion & ingénierie · accès libre · plusieurs n°/an'),
  ('revue-savart', 'Savart', 'https://cen-champagne-ardenne.org/telechargements', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'CEN Champagne-Ardenne · Gestion & ingénierie · accès libre (Publié depuis 1990.)'),
  ('revue-bulletin-du-musee-dhistoire-naturelle-de', 'Bulletin du Musée d''Histoire Naturelle de Colmar', 'https://www.museumcolmar.org/bulletin', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'Musée d''Histoire Naturelle et d''Ethnographie de Colmar · Généraliste · accès libre · annuel'),
  ('revue-publications-bufo', 'Publications BUFO', 'https://www.bufo-alsace.org/publication/', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'BUFO — amphibiens et reptiles d''Alsace · Herpétologie · accès libre · série numérotée (Monographies de l''herpétofaune d''Alsace.)'),
  ('revue-faune-champagne-ardenne-infos', 'Faune Champagne-Ardenne Infos', 'https://champagne-ardenne.lpo.fr/images/mediatheque/fichiers/Etudes/Connaissance/lettre_info_fca/9_faune_champagne-ardenne_info_decembre2017_fevrier2018.pdf', 'page suivie', 'régional', 'Grand Est', '', 'mensuelle', 'LPO Champagne-Ardenne · Ornithologie · accès libre · parution incertaine (Dernier numéro localisé : n°9, 2017-2018.)'),
  ('revue-bfc-nature', 'BFC Nature', 'https://bfcnature.fr/la-revue-scientifique-bfc-nature/', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'Bourgogne-Franche-Comté Nature · Généraliste · accès mixte · semestriel (Numéros 1 à 36 gratuits dans la limite des stocks.)'),
  ('revue-bulletin-de-la-shna-ofab', 'Bulletin de la SHNA-OFAB', 'https://www.shna-ofab.fr/nos-publications/le-bulletin-de-la-societe/', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'Société d''Histoire Naturelle d''Autun · Généraliste · accès mixte · semestriel (Anciens numéros sur Gallica.)'),
  ('revue-lazure', 'L''Azuré', 'https://cen-franchecomte.org/documentation/revues/lazure/', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'CEN Franche-Comté · Gestion & ingénierie · accès libre · irrégulier (Revue des gestionnaires de milieux naturels remarquables.)'),
  ('revue-le-sabot-de-venus', 'Le Sabot de Vénus', 'https://cen-franchecomte.org/documentation/revues/le-sabot-de-venus/', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'CEN Bourgogne et CEN Franche-Comté · Gestion & ingénierie · adhérents/abonnement · semestriel'),
  ('revue-echos-des-forets', 'Échos des forêts', 'https://forets-parcnational.fr/fr/publications-et-documents', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'Parc national de forêts · Forêt · accès libre · semestriel'),
  ('revue-la-feuille-de-neomys', 'La Feuille de Neomys', 'https://ressources.shna-ofab.fr/shna-ofab/fichiers__pdf_/3-ressources/1-publications/2-feuilles_de_neomys/1999_feuille_de_neomys_n3.pdf', 'page suivie', 'régional', 'Bourgogne-Franche-Comté', '', 'mensuelle', 'SHNA-OFAB · Mammifères & chiroptères · accès libre · parution incertaine (Micromammifères ; dernier numéro identifié ancien.)'),
  ('revue-bulletin-de-lanvl', 'Bulletin de l''ANVL', 'https://www.anvl.fr/nos-ressources/bulletins-de-lanvl/', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'Naturalistes de la Vallée du Loing et du massif de Fontainebleau · Généraliste · accès libre · annuel'),
  ('revue-le-passer', 'Le Passer', 'https://lpo-idf.fr/site/_fichiers/passer/LePasser_50_1.pdf', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'LPO Île-de-France (ex-CORIF) · Ornithologie · adhérents/abonnement · semestriel (Lien vers un numéro ; collection sur lpo-idf.fr.)'),
  ('revue-lepeichette', 'L''Épeichette', 'https://www.lpo-idf.fr/site/_fichiers/epeichette/Epeichette_121.pdf', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'LPO Île-de-France · Ornithologie · adhérents/abonnement · mensuel (Bulletin de liaison ; lien vers le n°121.)'),
  ('revue-bulletin-des-naturalistes-parisiens', 'Bulletin des Naturalistes Parisiens', 'https://www.lesnaturalistesparisiens.org/publications', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'Les Naturalistes Parisiens · Généraliste · adhérents/abonnement · parution incertaine'),
  ('revue-publications-du-cbnbp', 'Publications du CBNBP', 'https://cbnbp.mnhn.fr/cbnbp/ressources/publications.jsp', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'Conservatoire botanique national du Bassin parisien · Botanique & phytosociologie · accès mixte (Couvre aussi Centre, Bourgogne et Champagne-Ardenne.)'),
  ('revue-lettre-dinformation-1', 'Lettre d''information', 'https://www.cen-idf.fr/page/1674017-publications', 'page suivie', 'régional', 'Île-de-France', '', 'mensuelle', 'CEN Île-de-France · Gestion & ingénierie · accès libre · arrêtée (Interrompue après le n°26 (2021) ; nouvelle publication annoncée.)'),
  ('revue-loutarde', 'L''Outarde', 'https://www.lpo.fr/lpo-locales/la-lpo-en-nouvelle-aquitaine/lpo-poitou-charentes/nos-publications/revue-et-lettres-d-info-naturalistes2/l-outarde', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'LPO Poitou-Charentes · Ornithologie · accès libre · annuel (PDF gratuits ; n°61 pour 2026.)'),
  ('revue-le-courbageot', 'Le Courbageot', 'https://faune-aquitaine.org/index.php?item=17&m_id=1183', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'LPO Aquitaine · Ornithologie · accès libre · irrégulier'),
  ('revue-la-cistude', 'La Cistude', 'https://www.ne17.fr/revue-la-cistude/', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'Nature Environnement 17 · Généraliste · adhérents/abonnement · parution incertaine (Charente-Maritime ; conditions d''accès non confirmées.)'),
  ('revue-la-revue-naturaliste', 'La revue naturaliste', 'https://dsne.org/nos-publications/la-revue-naturaliste/', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'Deux-Sèvres Nature Environnement · Généraliste · adhérents/abonnement · parution incertaine'),
  ('revue-le-casseur-dos', 'Le Casseur d''Os', 'http://www.xn--gopa-pyrnes-ibbb.fr/le-casseur-dos/', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'Groupe Ornithologique des Pyrénées et de l''Adour · Ornithologie · adhérents/abonnement · annuel · parution incertaine (Site instable (boucles de redirection) ; existence de la revue confirmée par ailleurs.)'),
  ('revue-actes-de-la-societe-linneenne-de-bordeau', 'Actes de la Société Linnéenne de Bordeaux', 'https://linneenne-bordeaux.wixsite.com/slbx/bulletins', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'Société Linnéenne de Bordeaux · Généraliste · accès mixte · 4 n°/an (Sommaires en libre accès, numéros vendus à l''unité.)'),
  ('revue-bulletin-de-la-societe-de-borda', 'Bulletin de la Société de Borda', 'https://www.societe-borda.com/', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'Société de Borda · Généraliste · adhérents/abonnement · trimestriel (Landes ; sciences naturelles et histoire locale.)'),
  ('revue-centre-de-ressources-documentaires', 'Centre de ressources documentaires', 'https://documentation.cbnsa.fr/opac_css/index.php', 'page suivie', 'régional', 'Nouvelle-Aquitaine', '', 'mensuelle', 'CBN Sud-Atlantique · Botanique & phytosociologie · accès libre'),
  ('revue-ressources-et-publications', 'Ressources et publications', 'https://www.natureo.org/ressources/', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'Nature en Occitanie · Généraliste · accès libre · ponctuel'),
  ('revue-bulletin-de-la-societe-dhistoire-naturel', 'Bulletin de la Société d''Histoire Naturelle de Toulouse', 'https://shnt.fr/bulletin.html', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'SHNT · Généraliste · adhérents/abonnement (Toujours active (n°161 et suivants).)'),
  ('revue-isatis', 'Isatis', 'https://sbocc.fr/tout-isatis-dans-la-bibliotheque-de-la-sbocc/', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'Société Botanique d''Occitanie · Botanique & phytosociologie · accès libre · annuel (Bibliothèque numérique depuis 2001.)'),
  ('revue-lettres-dinformation', 'Lettres d''information', 'https://www.cen-occitanie.org/analyses-environnement-occitanie/', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'CEN Occitanie · Gestion & ingénierie · accès libre · saisonnier'),
  ('revue-empreintes', 'Empreintes', 'https://www.pyrenees-parcnational.fr/sites/pyrenees-parcnational.fr/files/2025-07/MAG_EMPREINTES_50_web.pdf', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'Parc national des Pyrénées · Gestion & ingénierie · accès libre (Lien vers le n°50 (2025).)'),
  ('revue-journal-du-parc', 'Journal du Parc', 'https://www.cevennes-parcnational.fr/fr/journal-du-parc', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'Parc national des Cévennes · Gestion & ingénierie · accès libre'),
  ('revue-portail-documentaire', 'Portail documentaire', 'https://biblio.cbnpmp.fr/', 'page suivie', 'régional', 'Occitanie', '', 'mensuelle', 'CBN des Pyrénées et de Midi-Pyrénées · Botanique & phytosociologie · accès libre'),
  ('revue-faune-paca-publication', 'Faune-PACA Publication', 'https://paca.lpo.fr/association-protection-nature/s-informer/editions/faune-paca-publication', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'LPO PACA · Généraliste · accès libre · très régulier (n°132 atteint mi-2025 ; études naturalistes et atlas.)'),
  ('revue-garrigues', 'Garrigues', 'https://cen-paca.org/decouvrir/les-actualites/', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'CEN PACA · Gestion & ingénierie · accès libre'),
  ('revue-la-nycteribie', 'La Nycteribie', 'https://www.gcprovence.org/wp-content/uploads/2024/07/2023_Nycteribie2022_VF_compresse-1.pdf', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Groupe Chiroptères de Provence · Mammifères & chiroptères · accès libre · annuel (Lien vers l''édition 2022-2023.)'),
  ('revue-bulletin-de-la-societe-linneenne-de-prov', 'Bulletin de la Société Linnéenne de Provence', 'https://www.linneenne-provence.org/bulletin.htm', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Société Linnéenne de Provence · Généraliste · accès libre · annuel (Articles également déposés sur Zenodo depuis 2026.)'),
  ('revue-chroniques-de-haute-provence', 'Chroniques de Haute-Provence', 'https://livre.tourisme-alpes-haute-provence.com/societe-scientifique-et-litteraire/', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Société Scientifique et Littéraire des Alpes-de-Haute-Provence · Généraliste · adhérents/abonnement (Ex-Annales des Basses-Alpes ; n°389 et suivants.)'),
  ('revue-magazine-du-parc', 'Magazine du Parc', 'https://mercantour-parcnational.fr/fr/categories-dactualite/publications', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Parc national du Mercantour · Gestion & ingénierie · accès libre'),
  ('revue-la-calanquaise', 'La Calanquaise', 'https://www.calanques-parcnational.fr/fr/publications-et-documents', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Parc national des Calanques · Gestion & ingénierie · accès libre · semestriel'),
  ('revue-travaux-scientifiques-du-parc-national-d', 'Travaux scientifiques du Parc national de Port-Cros', 'https://www.portcros-parcnational.fr/fr/rapports-scientifiques', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Parc national de Port-Cros et Porquerolles · Marin & littoral · accès libre · annuel (Volume 37 récent.)'),
  ('revue-lattitude', 'L''Attitude', 'https://www.portcros-parcnational.fr/fr/le-parc-national-de-port-cros/le-magazine-du-parc-national', 'page suivie', 'régional', 'Provence-Alpes-Côte d''Azur', '', 'mensuelle', 'Parc national de Port-Cros et Porquerolles · Marin & littoral · accès libre'),
  ('revue-leffraie', 'L''Effraie', 'https://auvergne-rhone-alpes.lpo.fr/leffraie-la-revue-naturaliste-de-la-lpo-dans-le-rhone-61-nouveau-numero/', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'LPO Rhône (LPO AuRA) · Ornithologie · accès libre (n°61 atteint.)'),
  ('revue-le-grand-duc', 'Le Grand-Duc', 'https://www.faune-aura.org/index.php?m_id=20283', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'LPO Auvergne (LPO AuRA) · Ornithologie · accès mixte · annuel · parution incertaine (Parution après 2022 non confirmée.)'),
  ('revue-biblio-lpo-aura', 'Biblio LPO AuRA', 'https://biblio.lpo-aura.org/', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'LPO AuRA et partenaires · Données & référentiels · accès libre (Base documentaire : atlas, listes rouges, guides techniques.)'),
  ('revue-bulletin-mensuel-de-la-societe-linneenne', 'Bulletin mensuel de la Société Linnéenne de Lyon', 'https://www.linneenne-lyon.org/spip3/spip.php?rubrique23=', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'Société Linnéenne de Lyon · Généraliste · adhérents/abonnement · mensuel'),
  ('revue-bulletin-mycologique-et-botanique-dauphi', 'Bulletin mycologique et botanique Dauphiné-Savoie', 'https://fmbds.org/bulletin/', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'Fédération mycologique et botanique Dauphiné-Savoie · Mycologie & cryptogames · accès mixte · trimestriel (Numéros antérieurs à 2010 en libre téléchargement.)'),
  ('revue-sylvae', 'Sylvae', 'https://cen-auvergne.fr/publications/lettres-d-informations/lettre-d-information-sylvae', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'CEN Auvergne · Gestion & ingénierie · accès libre'),
  ('revue-lecho-des-ecrins', 'L''écho des Écrins', 'https://www.ecrins-parcnational.fr/actualite/lecho-des-ecrins-et-un-cahier-thematique-sur-les-sentiers', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'Parc national des Écrins · Gestion & ingénierie · accès mixte · semestriel'),
  ('revue-mail-toutes-fleurs', 'Mail toutes fleurs', 'https://cbn-alpin.fr/actualites/mail-toutes-fleurs', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'CBN alpin (Gap-Charance) · Botanique & phytosociologie · accès libre · parution incertaine (Archives s''arrêtant en 2013 mais toujours listée par le CBN.)'),
  ('revue-e-folia-et-a-fleur-de-massif', 'E-Folia et À fleur de massif', 'https://www.cbnmc.fr/33-ressources/96-suivre-notre-activite/97-supports-information/98-lettre-information', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'CBN du Massif central · Botanique & phytosociologie · accès libre · parution incertaine'),
  ('revue-journal-espaces-naturels-de-rhone-alpes', 'Journal Espaces naturels de Rhône-Alpes', 'https://www.cen-rhonealpes.fr/les-publications-du-conservatoire/espaces-naturels/', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'CEN Rhône-Alpes · Gestion & ingénierie · accès libre · arrêtée (Dernier numéro repéré : n°22 (2019).)'),
  ('revue-travaux-scientifiques-du-parc-national-d-1', 'Travaux scientifiques du Parc national de la Vanoise', 'https://www.vanoise-parcnational.fr/fr/des-connaissances/recueil-et-partage-des-connaissances/revue-des-travaux-scientifiques-du-parc', 'page suivie', 'régional', 'Auvergne-Rhône-Alpes', '', 'mensuelle', 'Parc national de la Vanoise · Gestion & ingénierie · accès libre · arrêtée (24 volumes numérisés, 1970-2009 ; arrêt en 2013.)'),
  ('revue-bulletin-de-la-societe-des-sciences-hist', 'Bulletin de la Société des Sciences Historiques et Naturelles de la Corse', 'https://www.societesciencescorse.fr/les-publications/', 'page suivie', 'régional', 'Corse', '', 'mensuelle', 'SSHNC · Généraliste · adhérents/abonnement (Paraît sans interruption depuis 1881 ; n°788-789 en 2024-2025.)'),
  ('revue-courrier-du-parc', 'Courrier du Parc', 'https://www.pnr.corsica/fr/infos-telechargement', 'page suivie', 'régional', 'Corse', '', 'mensuelle', 'Parc naturel régional de Corse · Gestion & ingénierie · accès libre (36 numéros repérés.)'),
  ('revue-cahiers-scientifiques-du-parc-amazonien-', 'Cahiers scientifiques du Parc amazonien de Guyane', 'https://www.parc-amazonien-guyane.fr/fr/publications-et-documents', 'page suivie', 'régional', 'Outre-mer', '', 'mensuelle', 'Parc amazonien de Guyane · Généraliste · accès libre · irrégulier (Environ 8 numéros ; n°8 en août 2025.)'),
  ('revue-publications-et-documents', 'Publications et documents', 'https://www.guadeloupe-parcnational.fr/fr/publications-et-documents', 'page suivie', 'régional', 'Outre-mer', '', 'mensuelle', 'Parc national de la Guadeloupe · Généraliste · accès libre · au fil de l''eau'),
  ('revue-publications-et-documents-1', 'Publications et documents', 'https://www.reunion-parcnational.fr/fr/publications-and-documents', 'page suivie', 'régional', 'Outre-mer', '', 'mensuelle', 'Parc national de La Réunion · Gestion & ingénierie · accès libre · annuel (rapport) (Restauration écologique et flore indigène.)'),
  ('revue-newsletter-rizhom', 'Newsletter RiZHOM', 'https://www.pole-tropical.org/actualites/newsletter/', 'page suivie', 'régional', 'Outre-mer', '', 'mensuelle', 'Pôle-relais zones humides tropicales · Zones humides · accès libre · plusieurs n°/an')
on conflict (id) do nothing;
